export const treedata =[
    {
        title:'1楼',
        value:'T-1',
        children:[
            {
                title:'T1',
                value:'T1'
            }
        ]
    },
    {
        title:'2楼',
        value:'T2',
        children:[
            {
                title:'T201',
                value:'T201'
            },
            {
                title:'T202',
                value:'T202'
            },
            {
                title:'T203',
                value:'T203'
            },
            {
                title:'T204',
                value:'T204'
            },
            {
                title:'T205',
                value:'T205'
            },
            {
                title:'T206',
                value:'T206'
            },
            {
                title:'T207',
                value:'T207'
            },
            {
                title:'T208',
                value:'T208'
            },
            {
                title:'T209',
                value:'T209'
            },
            {
                title:'T210',
                value:'T210'
            },
            {
                title:'T211',
                value:'T211'
            },
            {
                title:'T212',
                value:'T212'
            },
            {
                title:'T213',
                value:'T213'
            },
            {
                title:'T214',
                value:'T214'
            },
            {
                title:'T215',
                value:'T215'
            },
            {
                title:'T216',
                value:'T216'
            },
            {
                title:'T217',
                value:'T217'
            },
            {
                title:'T218',
                value:'T218'
            },
            {
                title:'T219',
                value:'T219'
            },
            {
                title:'大货区2',
                value:'大货区2'
            }
        ]
    },
    {
        title:'3楼',
        value:'T3',
        children:[
            {
                title:'T301',
                value:'T301'
            },
            {
                title:'T302',
                value:'T302'
            },
            {
                title:'T303',
                value:'T303'
            },
            {
                title:'T304',
                value:'T304'
            },
            {
                title:'T305',
                value:'T305'
            },
            {
                title:'T306',
                value:'T306'
            },
            {
                title:'T307',
                value:'T307'
            },
            {
                title:'T308',
                value:'T308'
            },
            {
                title:'T309',
                value:'T309'
            },
            {
                title:'T310',
                value:'T310'
            },
            {
                title:'T311',
                value:'T311'
            },
            {
                title:'T312',
                value:'T312'
            },
            {
                title:'T313',
                value:'T313'
            },
            {
                title:'T314',
                value:'T314'
            },
            {
                title:'T315',
                value:'T315'
            },
            {
                title:'T316',
                value:'T316'
            },
            {
                title:'T317',
                value:'T317'
            },
            {
                title:'T318',
                value:'T318'
            },
            {
                title:'T319',
                value:'T319'
            },
            {
                title:'T320',
                value:'T320'
            },
            {
                title:'大货区3',
                value:'大货区3'
            }
        ]
    },
    {
        title:'4楼',
        value:'T4',
        children:[
            {
                title:'T401',
                value:'T401'
            },
            {
                title:'T402',
                value:'T402'
            },
            {
                title:'T403',
                value:'T403'
            },
            {
                title:'T404',
                value:'T404'
            },
            {
                title:'T405',
                value:'T405'
            },
            {
                title:'T406',
                value:'T406'
            },
            {
                title:'T407',
                value:'T407'
            },
            {
                title:'T408',
                value:'T408'
            },
            {
                title:'T409',
                value:'T409'
            },
            {
                title:'T410',
                value:'T410'
            },
            {
                title:'T411',
                value:'T411'
            },
            {
                title:'T412',
                value:'T412'
            },
            {
                title:'T413',
                value:'T413'
            },
            {
                title:'T414',
                value:'T414'
            },
            {
                title:'T415',
                value:'T415'
            },
            {
                title:'T416',
                value:'T416'
            },
            {
                title:'T417',
                value:'T417'
            },
            {
                title:'T418',
                value:'T418'
            },
            {
                title:'T419',
                value:'T419'
            },
            {
                title:'T420',
                value:'T420'
            },
            {
                title:'大货区4',
                value:'大货区4'
            }
        ]
    },
    {
        title:'5楼',
        value:'T5',
        children:[
            {
                title:'T501',
                value:'T501'
            },
            {
                title:'T502',
                value:'T502'
            },
            {
                title:'T503',
                value:'T503'
            },
            {
                title:'T504',
                value:'T504'
            },
            {
                title:'T505',
                value:'T505'
            },
            {
                title:'T506',
                value:'T506'
            },
            {
                title:'T507',
                value:'T507'
            },
            {
                title:'T508',
                value:'T508'
            },
            {
                title:'T509',
                value:'T509'
            },
            {
                title:'T510',
                value:'T510'
            },
            {
                title:'T511',
                value:'T511'
            },
            {
                title:'T512',
                value:'T512'
            },
            {
                title:'T513',
                value:'T513'
            },
            {
                title:'T514',
                value:'T514'
            },
            {
                title:'T515',
                value:'T515'
            },
            {
                title:'T516',
                value:'T516'
            },
            {
                title:'T517',
                value:'T517'
            },
            {
                title:'T518',
                value:'T518'
            },
            {
                title:'T519',
                value:'T519'
            },
            {
                title:'T520',
                value:'T520'
            },
            {
                title:'T521',
                value:'T521'
            },
            {
                title:'T522',
                value:'T522'
            },
            {
                title:'T523',
                value:'T523'
            },
            {
                title:'T524',
                value:'T524'
            },
            {
                title:'T525',
                value:'T525'
            },
            {
                title:'T526',
                value:'T526'
            },
            {
                title:'T527',
                value:'T527'
            },
            {
                title:'大货区5',
                value:'大货区5'
            }
        ]
    }
];

export default{
    treedata
}